export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  TOO_LARGE: "TOO_LARGE",
  SCHEMA_MISMATCH: "SCHEMA_MISMATCH",
  UNSUPPORTED_FORMAT: "UNSUPPORTED_FORMAT",
  UNSUPPORTED_CLIPBOARD_KIND: "UNSUPPORTED_CLIPBOARD_KIND",
  MODE_LOCK_VIOLATION: "MODE_LOCK_VIOLATION",
  QUEUE_BACKPRESSURE: "QUEUE_BACKPRESSURE",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
