packages:
  - .

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - fast-uri
strictDepBuilds: true
allowBuilds: {}
dangerouslyAllowAllBuilds: false
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
