export const STAGE_ARTIFACT_KEYS = {
  figmaRaw: "figma.raw",
  figmaCleaned: "figma.cleaned",
  figmaCleanedReport: "figma.cleaned.report",
  figmaFetchDiagnostics: "figma.fetch_diagnostics",
  figmaHybridEnrichment: "figma.hybrid.enrichment",
  customerProfileResolved: "customer.profile.resolved",
  regenerationSourceIr: "regeneration.source_ir",
  regenerationOverrides: "regeneration.overrides",
  designIr: "design.ir",
  figmaAnalysis: "figma.analysis",
  storybookCatalog: "storybook.catalog",
  storybookEvidence: "storybook.evidence",
  storybookTokens: "storybook.tokens",
  storybookThemes: "storybook.themes",
  storybookComponents: "storybook.components",
  componentVisualCatalog: "storybook.component_visual_catalog",
  figmaLibraryResolution: "figma.library_resolution",
  componentMatchReport: "component.match_report",
  generatedProject: "generated.project",
  codegenSummary: "codegen.summary",
  generationMetrics: "generation.metrics",
  componentManifest: "component.manifest",
  generationDiffContext: "generation.diff.context",
  generationDiff: "generation.diff",
  generationDiffFile: "generation.diff.file",
  visualAuditReferenceImage: "visual.audit.reference_image",
  visualAuditActualImage: "visual.audit.actual_image",
  visualAuditDiffImage: "visual.audit.diff_image",
  visualAuditReport: "visual.audit.report",
  visualAuditResult: "visual.audit.result",
  visualQualityReport: "visual.quality.report",
  visualQualityResult: "visual.quality.result",
  compositeQualityReport: "composite.quality.report",
  compositeQualityResult: "composite.quality.result",
  confidenceReport: "confidence.report",
  confidenceResult: "confidence.result",
  validationSummary: "validation.summary",
  validationSummaryFile: "validation.summary.file",
  reproPath: "repro.path",
  gitPrStatus: "git.pr.status",
} as const;

export type StageArtifactKey =
  | (typeof STAGE_ARTIFACT_KEYS)[keyof typeof STAGE_ARTIFACT_KEYS]
  | (string & {});
