// ---------------------------------------------------------------------------
// generator-templates.ts — Slim orchestrator (re-exports from templates/)
// Sub-modules: utility-functions, icon-template, form-template, screen-template,
//              theme-template, error-boundary-template, app-template
// See issue #298 for the decomposition rationale.
// ---------------------------------------------------------------------------

// ── Re-exports from generator-responsive.js (unchanged) ─────────────────
export {
  RESPONSIVE_WIDTH_RATIO_MIN,
  RESPONSIVE_WIDTH_RATIO_MAX,
  RESPONSIVE_FULL_WIDTH_EPSILON,
  normalizeResponsiveWidthRatio,
  toPercentLiteralFromRatio,
  RESPONSIVE_BREAKPOINT_ORDER,
  MUI_DEFAULT_BREAKPOINT_VALUES,
  RESPONSIVE_FALLBACK_RESET_VALUE_BY_PROPERTY,
  toResponsiveSxValueLiteral,
  hasSameResponsiveSxValue,
  toSxValueMapFromEntries,
  pushResponsiveStyleEntry,
  appendLayoutOverrideEntriesForBreakpoint,
  toResponsivePropertyValueByBreakpoint,
  toResponsiveObjectLiteralForProperty,
  toResponsiveObjectEntries,
  toResponsiveLayoutMediaEntries,
  toResponsiveBaseLayoutValues,
  toScreenResponsiveRootMediaEntries,
  toResponsiveBreakpointValuesLiteral
} from "./generator-responsive.js";
export type { ResponsiveSxValue, ResponsiveSxEntry } from "./generator-responsive.js";

// ── Re-exports from templates/utility-functions.ts ──────────────────────
export {
  literal,
  clamp,
  normalizeOpacityForSx,
  normalizeFontFamily,
  toPxLiteral,
  DEFAULT_SPACING_BASE,
  REM_BASE,
  DEFAULT_ROUTER_MODE,
  normalizeSpacingBase,
  toSpacingUnitValue,
  toSpacingEdgeUnit,
  toBoxSpacingSxEntries,
  toThemeBorderRadiusValue,
  toRemLiteral,
  toEmLiteral,
  toLetterSpacingEm,
  normalizeHexColor,
  toRoundedIntegerInRange,
  resolveDeterministicIntegerSample,
  resolveDeterministicColorSample,
  withOmittedSxKeys,
  toThemePaletteLiteral,
  toThemeColorLiteral,
  BUTTON_FULL_WIDTH_EPSILON,
  BUTTON_VISIBLE_ALPHA_THRESHOLD,
  BUTTON_DISABLED_OPACITY_THRESHOLD,
  BUTTON_NEUTRAL_CHANNEL_DELTA_MAX,
  BUTTON_NEAR_WHITE_MIN_CHANNEL,
  FIELD_ERROR_RED_MIN_CHANNEL,
  FIELD_ERROR_RED_DELTA_MIN,
  DARK_MODE_BACKGROUND_DEFAULT,
  DARK_MODE_BACKGROUND_PAPER,
  DARK_MODE_TEXT_PRIMARY,
  LIGHTEN_TO_WHITE_STEP,
  LIGHTEN_TO_WHITE_MAX_STEPS,
  DEFAULT_FORM_HANDLING_MODE,
  resolveFormHandlingMode,
  hasVisibleGradient,
  toRgbaColor,
  isVisibleColor,
  isNearWhiteColor,
  isNeutralGrayColor,
  isLikelyErrorRedColor,
  toRelativeLuminance,
  toContrastRatio,
  toOpaqueHex,
  toHexChannel,
  toRgbHex,
  mixHexColors,
  toHexWithAlpha,
  ensureContrastAgainstBackground,
  buildActionPalette,
  toLightThemePalette,
  toDarkThemePalette,
  toThemePaletteBlock,
  inferButtonVariant,
  inferButtonSize,
  inferButtonFullWidth,
  inferButtonDisabled,
  filterButtonVariantEntries,
  mapPrimaryAxisAlignToJustifyContent,
  mapCounterAxisAlignToAlignItems,
  dedupeSxEntries,
  sxString,
  toPaintSxEntries,
  normalizeElevationForSx,
  matchesRoundedInteger,
  toShadowSxEntry,
  toVariantStateSxObject,
  appendVariantStateOverridesToSx,
  toChipVariant,
  toChipSize,
  inferChipSizeFromHeight,
  indentBlock,
  baseLayoutEntries,
  toElementSx,
  firstText,
  firstTextColor,
  collectTextNodes,
  collectVectorPaths,
  firstVectorColor,
  escapeXmlText,
  toRenderableAssetSource,
  deriveResponsiveThemeBreakpointValues,
  toMuiContainerMaxWidth,
  toAlertSeverityFromName,
  sanitizeSelectOptionValue
} from "./templates/utility-functions.js";
export type { ResolvedThemePalette } from "./templates/utility-functions.js";

// ── Re-exports from templates/icon-template.ts ──────────────────────────
export {
  renderFallbackIconExpression,
  renderInlineSvgIcon
} from "./templates/icon-template.js";

// ── Re-exports from templates/form-template.ts ──────────────────────────
export {
  buildInlineLegacyFormStateBlock,
  buildLegacyFormContextFile,
  toReactHookFormSchemaEntries,
  toCrossFieldRefineChain,
  buildInlineReactHookFormStateBlock,
  buildReactHookFormContextFile
} from "./templates/form-template.js";

// ── Re-exports from templates/theme-template.ts ─────────────────────────
export {
  toThemeSxStyleValueLiteral,
  createThemeComponentBlockDraft,
  appendC1ThemeStyleEntriesToDraft,
  renderThemeComponentBlock,
  storybookThemeFile,
  fallbackThemeFile
} from "./templates/theme-template.js";
export type { ThemeComponentBlockDraft } from "./templates/theme-template.js";

// ── Re-exports from templates/screen-template.ts ────────────────────────
export {
  renderText,
  renderButton,
  isPillShapedOutlinedButton,
  renderChildrenIntoParent,
  renderNodesIntoParent,
  SIMPLE_STACK_GEOMETRY_SX_KEYS,
  hasResponsiveTopLevelLayoutOverrides,
  hasVisibleBorderSignal,
  hasDistinctSurfaceFill,
  isElevatedSurfaceContainerForPaper,
  isSimpleFlexContainerForStack,
  toSimpleStackContainerSx,
  renderSimpleFlexContainerAsStack,
  renderListFromRows,
  collectRenderedItems,
  collectRenderedItemLabels,
  renderGridLayout,
  renderCard,
  renderChip,
  renderSelectionControl,
  renderList,
  isLikelyAppBarToolbarActionNode,
  renderStructuredAppBarToolbarChildren,
  renderAppBar,
  renderTabs,
  renderDialog,
  renderStepper,
  renderProgress,
  renderAvatar,
  renderBadge,
  renderDividerElement,
  renderNavigation,
  renderGrid,
  renderStack,
  renderPaper,
  renderTable,
  renderTooltipElement,
  renderDrawer,
  renderBreadcrumbs,
  renderSlider,
  renderSelectElement,
  renderRatingElement,
  renderSnackbar,
  renderSkeleton,
  isAboveTheFoldImage,
  renderImageElement,
  renderContainerIconWrapper,
  tryRenderAccordionContainer,
  tryRenderInputContainer,
  tryRenderPillShapedButtonContainer,
  tryRenderIconLikeContainer,
  tryRenderGridLikeContainer,
  tryRenderPaperSurfaceContainer,
  tryRenderRepeatedListContainer,
  tryRenderSimpleFlexContainer,
  CONTAINER_RENDER_STRATEGIES,
  renderContainerFallback,
  renderContainer,
  runElementPreDispatchStrategies,
  elementRenderStrategies,
  resolveElementRenderStrategy,
  renderElement,
  renderSemanticInput,
  renderSemanticAccordion,
  normalizeScreenTestTargetText,
  collectRepresentativeScreenTextTargets,
  normalizeRenderedScreenTextForSearch,
  filterTextTargetsByRenderedScreenOutput,
  collectRepresentativeScreenButtonTargets,
  collectRepresentativeFieldTargets,
  buildScreenTestTargetPlan,
  buildScreenUnitTestFile,
  prepareFallbackScreenModel,
  buildFallbackRenderState,
  assembleFallbackDependencies,
  composeFallbackScreenModule,
  appShellFile,
  fallbackScreenFile,
  wrappedFallbackScreenFile,
  MAX_SCREEN_TEST_TEXT_TARGETS,
  MAX_SCREEN_TEST_BUTTON_TARGETS,
  MAX_SCREEN_TEST_INPUT_TARGETS,
  MAX_SCREEN_TEST_SELECT_TARGETS,
  MAX_SCREEN_TEST_TARGET_TEXT_LENGTH,
  MIN_SCREEN_TEST_TEXT_ASSERTION_LENGTH
} from "./templates/screen-template.js";
export type {
  FallbackScreenFileResult,
  AppShellFileInput,
  ScreenTestButtonTarget,
  ScreenTestTargetPlan,
  FallbackScreenFileInput,
  PreparedFallbackScreenModel,
  FallbackRenderState,
  FallbackDependencyAssembly,
  WrappedFallbackScreenFileInput,
  ElementRenderStrategyInput,
  ContainerRenderStrategyMatch,
  ContainerRenderStrategy,
  ElementRenderStrategy,
  PreDispatchRenderStrategy,
  DetectedTabInterfacePattern,
  DetectedDialogOverlayPattern,
  DialogActionModel,
  RenderedItem
} from "./templates/screen-template.js";

// ── Re-exports from templates/error-boundary-template.ts ────────────────
export {
  makeErrorBoundaryFile,
  makeScreenSkeletonFile
} from "./templates/error-boundary-template.js";

// ── Re-exports from templates/app-template.ts ───────────────────────────
export {
  makeAppFile
} from "./templates/app-template.js";
