export interface IconFallbackCatalogEntry {
  iconName: string;
  aliases?: string[];
}

export interface IconFallbackCatalog {
  version: 1;
  entries: IconFallbackCatalogEntry[];
  synonyms: Record<string, string>;
}

export const ICON_FALLBACK_MAP_VERSION = 1 as const;

const BUILTIN_ICON_NAMES = [
  "Home",
  "HomeOutlined",
  "Menu",
  "Close",
  "Search",
  "ManageSearch",
  "Settings",
  "Tune",
  "Apps",
  "Dashboard",
  "Widgets",
  "MenuOpen",
  "MoreVert",
  "MoreHoriz",
  "ArrowBack",
  "ArrowForward",
  "ArrowBackIos",
  "ArrowForwardIos",
  "ArrowUpward",
  "ArrowDownward",
  "ArrowLeft",
  "ArrowRight",
  "West",
  "East",
  "North",
  "South",
  "ChevronLeft",
  "ChevronRight",
  "ExpandMore",
  "ExpandLess",
  "UnfoldMore",
  "FirstPage",
  "LastPage",
  "KeyboardArrowLeft",
  "KeyboardArrowRight",
  "KeyboardArrowUp",
  "KeyboardArrowDown",
  "SubdirectoryArrowLeft",
  "SubdirectoryArrowRight",
  "OpenWith",
  "SwapHoriz",
  "SwapVert",
  "CompareArrows",
  "SyncAlt",
  "Sync",
  "Replay",
  "Refresh",
  "Undo",
  "Redo",
  "Login",
  "Logout",
  "Launch",
  "OpenInNew",
  "Link",
  "ContentCopy",
  "ContentPaste",
  "ContentCut",
  "FilterList",
  "Sort",
  "Flag",
  "Bookmark",
  "BookmarkBorder",
  "Favorite",
  "FavoriteBorder",
  "Star",
  "StarBorder",
  "Grade",
  "ThumbUp",
  "ThumbDown",
  "Check",
  "CheckCircle",
  "CheckCircleOutline",
  "Done",
  "DoneAll",
  "Cancel",
  "Error",
  "ErrorOutline",
  "Warning",
  "Info",
  "InfoOutlined",
  "Help",
  "HelpOutline",
  "Report",
  "ReportProblem",
  "BugReport",
  "Build",
  "BuildCircle",
  "Construction",
  "Engineering",
  "Handyman",
  "Verified",
  "VerifiedUser",
  "Security",
  "Policy",
  "Gavel",
  "PrivacyTip",
  "HealthAndSafety",
  "Lock",
  "LockOpen",
  "LockReset",
  "VpnKey",
  "Key",
  "Shield",
  "ShieldOutlined",
  "Visibility",
  "VisibilityOff",
  "Person",
  "PersonOutline",
  "PersonAdd",
  "PersonRemove",
  "PersonSearch",
  "People",
  "Group",
  "Groups",
  "AccountCircle",
  "Badge",
  "SupervisorAccount",
  "Face",
  "EmojiPeople",
  "Diversity3",
  "HowToReg",
  "HowToVote",
  "Contacts",
  "ContactMail",
  "ContactPhone",
  "AlternateEmail",
  "Mail",
  "MailOutline",
  "Email",
  "Send",
  "MarkEmailRead",
  "Drafts",
  "Chat",
  "ChatBubble",
  "ChatBubbleOutline",
  "Forum",
  "Message",
  "Sms",
  "Textsms",
  "Comment",
  "QuestionAnswer",
  "Phone",
  "PhoneIphone",
  "PhoneAndroid",
  "Call",
  "CallEnd",
  "CallMade",
  "CallReceived",
  "Videocam",
  "VideocamOff",
  "Mic",
  "MicOff",
  "VolumeUp",
  "VolumeDown",
  "VolumeOff",
  "Notifications",
  "NotificationsNone",
  "NotificationsActive",
  "NotificationImportant",
  "RssFeed",
  "Campaign",
  "Announcement",
  "Public",
  "Language",
  "Translate",
  "GTranslate",
  "TravelExplore",
  "Explore",
  "NearMe",
  "Place",
  "LocationOn",
  "LocationOff",
  "PinDrop",
  "Map",
  "Navigation",
  "MyLocation",
  "LocationSearching",
  "Directions",
  "DirectionsCar",
  "DirectionsBus",
  "DirectionsWalk",
  "DirectionsBike",
  "Flight",
  "Train",
  "Subway",
  "TwoWheeler",
  "LocalTaxi",
  "Add",
  "AddCircle",
  "AddCircleOutline",
  "AddBox",
  "Remove",
  "RemoveCircle",
  "RemoveCircleOutline",
  "Delete",
  "DeleteOutline",
  "DeleteForever",
  "Edit",
  "EditOutlined",
  "EditNote",
  "ModeEdit",
  "Save",
  "SaveAs",
  "Create",
  "CreateNewFolder",
  "FileOpen",
  "Folder",
  "FolderOpen",
  "FolderShared",
  "DriveFileMove",
  "InsertDriveFile",
  "AttachFile",
  "Cloud",
  "CloudUpload",
  "CloudDownload",
  "CloudDone",
  "CloudOff",
  "CloudQueue",
  "Backup",
  "BackupTable",
  "Download",
  "DownloadForOffline",
  "Upload",
  "UploadFile",
  "FileUpload",
  "FileDownload",
  "Print",
  "IosShare",
  "Share",
  "ShareLocation",
  "ScreenShare",
  "Reply",
  "ReplyAll",
  "Forward",
  "Archive",
  "Unarchive",
  "MoveToInbox",
  "Inventory",
  "Inventory2",
  "LocalShipping",
  "LocalMall",
  "ShoppingCart",
  "ShoppingBasket",
  "ShoppingBag",
  "Store",
  "Storefront",
  "Receipt",
  "ReceiptLong",
  "Payment",
  "Payments",
  "CreditCard",
  "AccountBalance",
  "AccountBalanceWallet",
  "Savings",
  "AttachMoney",
  "CurrencyExchange",
  "PriceCheck",
  "Sell",
  "SellOutlined",
  "Loyalty",
  "LocalOffer",
  "Redeem",
  "RequestQuote",
  "Paid",
  "MonetizationOn",
  "AccountTree",
  "CallSplit",
  "DeviceHub",
  "Hub",
  "Insights",
  "AutoGraph",
  "BarChart",
  "PieChart",
  "ShowChart",
  "Timeline",
  "StackedLineChart",
  "QueryStats",
  "Analytics",
  "Assessment",
  "Poll",
  "Leaderboard",
  "Score",
  "TrendingUp",
  "TrendingDown",
  "Equalizer",
  "DataUsage",
  "InsertChart",
  "TableChart",
  "ViewList",
  "ViewModule",
  "ViewQuilt",
  "GridView",
  "TableRows",
  "TableRowsOutlined",
  "List",
  "ListAlt",
  "FormatListBulleted",
  "Checklist",
  "Reorder",
  "DragIndicator",
  "ViewAgenda",
  "ViewWeek",
  "ViewDay",
  "Subject",
  "TextFields",
  "Title",
  "Notes",
  "Description",
  "Article",
  "Feed",
  "Newspaper",
  "Topic",
  "History",
  "HistoryToggleOff",
  "Event",
  "EventAvailable",
  "EventBusy",
  "EventNote",
  "CalendarMonth",
  "Today",
  "DateRange",
  "Schedule",
  "AccessTime",
  "AccessTimeFilled",
  "Alarm",
  "AlarmOn",
  "AlarmOff",
  "Timer",
  "AvTimer",
  "Update",
  "WatchLater",
  "Pending",
  "PlayArrow",
  "Pause",
  "Stop",
  "PlayCircle",
  "PauseCircle",
  "StopCircle",
  "SkipNext",
  "SkipPrevious",
  "FastForward",
  "FastRewind",
  "Repeat",
  "Shuffle",
  "MusicNote",
  "QueueMusic",
  "Album",
  "LibraryMusic",
  "Movie",
  "LocalMovies",
  "OndemandVideo",
  "LiveTv",
  "Image",
  "ImageOutlined",
  "ImageSearch",
  "Photo",
  "PhotoCamera",
  "Camera",
  "CameraAlt",
  "Collections",
  "CollectionsBookmark",
  "Wallpaper",
  "Brush",
  "ColorLens",
  "FormatPaint",
  "Palette",
  "Draw",
  "Gesture",
  "AutoFixHigh",
  "Style",
  "WbSunny",
  "Nightlight",
  "NightsStay",
  "DarkMode",
  "LightMode",
  "Brightness4",
  "Brightness7",
  "Bolt",
  "Power",
  "PowerOff",
  "BatteryFull",
  "BatteryAlert",
  "BatteryChargingFull",
  "ElectricalServices",
  "FlashOn",
  "FlashOff",
  "Wifi",
  "WifiOff",
  "Bluetooth",
  "BluetoothConnected",
  "SignalWifi4Bar",
  "Router",
  "Lan",
  "Devices",
  "DevicesOther",
  "DesktopWindows",
  "Laptop",
  "TabletMac",
  "Smartphone",
  "Watch",
  "Memory",
  "Storage",
  "SdStorage",
  "CloudCircle",
  "Dns",
  "DataObject",
  "Terminal",
  "Code",
  "DeveloperMode",
  "Api",
  "IntegrationInstructions",
  "Science",
  "Biotech",
  "School",
  "MenuBook",
  "ImportContacts",
  "AutoStories",
  "WorkspacePremium",
  "Work",
  "Business",
  "Apartment",
  "CorporateFare",
  "Domain",
  "Factory",
  "CardMembership",
  "MilitaryTech",
  "LocalHospital",
  "MedicalServices",
  "Medication",
  "LocalPharmacy",
  "Vaccines",
  "Healing",
  "MonitorHeart",
  "BabyChangingStation",
  "Pets",
  "Park",
  "SportsSoccer",
  "SportsBasketball",
  "SportsEsports",
  "FitnessCenter",
  "SelfImprovement",
  "Spa",
  "Restaurant",
  "LocalCafe",
  "LocalBar",
  "Hotel",
  "Bed",
  "KingBed",
  "Bathtub",
  "Weekend",
  "Chair",
  "CheckBox",
  "CheckBoxOutlineBlank",
  "IndeterminateCheckBox",
  "RadioButtonChecked",
  "RadioButtonUnchecked",
  "ToggleOn",
  "ToggleOff",
  "Circle",
  "Lens",
  "PanoramaFishEye",
  "DoNotDisturb",
  "DoNotDisturbOn",
  "Block",
  "HighlightOff",
  "CloseFullscreen",
  "OpenInFull",
  "Fullscreen",
  "FullscreenExit"
] as const;

export const BUILTIN_ICON_FALLBACK_CATALOG: IconFallbackCatalog = {
  version: ICON_FALLBACK_MAP_VERSION,
  entries: BUILTIN_ICON_NAMES.map((iconName) => ({ iconName })),
  synonyms: {
  "user": "Person",
  "users": "People",
  "trash": "Delete",
  "trashcan": "Delete",
  "bin": "Delete",
  "garbage": "Delete",
  "remove": "Remove",
  "plus": "Add",
  "minus": "Remove",
  "mail": "Mail",
  "email": "Email",
  "phone": "Phone",
  "chat": "Chat",
  "message": "Message",
  "notify": "Notifications",
  "notification": "Notifications",
  "avatar": "Person",
  "profile": "Person",
  "account": "AccountCircle",
  "settings": "Settings",
  "config": "Settings",
  "gear": "Settings",
  "cog": "Settings",
  "download": "Download",
  "upload": "Upload",
  "print": "Print",
  "refresh": "Refresh",
  "reload": "Refresh",
  "share": "Share",
  "favorite": "Favorite",
  "favourite": "Favorite",
  "like": "ThumbUp",
  "dislike": "ThumbDown",
  "star": "Star",
  "bookmark": "Bookmark",
  "copy": "ContentCopy",
  "paste": "ContentPaste",
  "filter": "FilterList",
  "sort": "Sort",
  "folder": "Folder",
  "file": "InsertDriveFile",
  "attachment": "AttachFile",
  "home": "Home",
  "house": "Home",
  "help": "Help",
  "info": "Info",
  "warning": "Warning",
  "error": "Error",
  "arrow left": "ArrowBack",
  "arrow right": "ArrowForward",
  "left arrow": "ArrowBack",
  "right arrow": "ArrowForward",
  "chevron left": "ChevronLeft",
  "chevron right": "ChevronRight",
  "down arrow": "ArrowDownward",
  "up arrow": "ArrowUpward",
  "calendar": "CalendarMonth",
  "time": "AccessTime",
  "clock": "AccessTime",
  "location": "LocationOn",
  "map": "Map",
  "link": "Link",
  "external": "OpenInNew",
  "cart": "ShoppingCart",
  "shop": "Store",
  "payment": "Payment",
  "credit card": "CreditCard",
  "money": "AttachMoney",
  "chart": "BarChart",
  "graph": "AutoGraph",
  "analytics": "Analytics",
  "camera": "CameraAlt",
  "photo": "Photo",
  "image": "Image",
  "video": "Videocam",
  "play": "PlayArrow",
  "pause": "Pause",
  "stop": "Stop",
  "mic": "Mic",
  "wifi": "Wifi",
  "bluetooth": "Bluetooth",
  "code": "Code",
  "terminal": "Terminal",
  "cloud": "Cloud",
  "search person": "PersonSearch",
  "person search": "PersonSearch",
  "personensuche": "PersonSearch",
  "hilfe": "HelpOutline",
  "startseite": "HomeOutlined",
  "merken": "BookmarkBorder",
  "questionmark": "HelpOutline",
  "speechbubble": "Forum",
  "speech bubble": "Forum",
  "messenger": "Forum",
  "homepage": "HomeOutlined"
}
};
