export type {
  DeploymentProfile,
  EditSessionState,
  FigmaMcpAuthMode,
  FigmaSourceMode,
  JobEventType,
  JobExecutionMode,
  JobPreviewState,
  JobQueueStatus,
  JobStageState,
  JobState,
  JobWarningCode,
  LlmApiKeyMode,
  LlmCodegenMode,
  LlmEndpointMode,
  LlmProviderMode,
  MappingGateMode,
  RepoAuthSource,
  SyncChangeClass,
  SyncRunResultStatus,
  SyncRunStatus,
  UiGateMode,
  ValidatorInstallPolicy
} from "./types-core.js";

export type {
  BoardRegistryRecord,
  CredentialProfileMetadata,
  CredentialProfilePayload,
  CredentialProfileRecord,
  CredentialRef,
  DiffFile,
  DiffStats,
  PatchPlan,
  PatchPlanStepDelete,
  PatchPlanStepWrite,
  SyncBranchPolicy,
  SyncChangeRecord,
  SyncDiffEvidence,
  SyncDiffHunk,
  SyncDiffLine,
  SyncFailPolicy,
  SyncPolicy,
  SyncPolicySchedule,
  SyncRunRecord,
  SyncRunSummary,
  UiGatePolicy
} from "./types-sync.js";

export type {
  ComponentMappingCoverage,
  ComponentMappingRule,
  ComponentMappingSource,
  MappingCoverageMetrics,
  MappingPolicy
} from "./types-mapping.js";

export { validateDesignIR } from "./types-ir.js";

export type {
  CounterAxisAlignItems,
  DepthTruncatedScreenMetric,
  DesignIR,
  DesignManifest,
  DesignNodeFingerprint,
  DesignScreenFingerprint,
  DesignIrDarkPaletteHints,
  DesignIrThemeAnalysis,
  DesignTokenActionPalette,
  DesignTokenPalette,
  DesignTokenTypographyScale,
  DesignTokenTypographyVariant,
  DesignTokenTypographyVariantName,
  DesignTokens,
  GeneratedFile,
  GenerationMetrics,
  PrimaryAxisAlignItems,
  ResponsiveBreakpoint,
  ScreenElementCountMetric,
  ScreenElementIR,
  ScreenIR,
  ScreenResponsiveIR,
  ScreenResponsiveLayoutOverride,
  ScreenResponsiveLayoutOverridesByBreakpoint,
  ScreenResponsiveVariantIR,
  ScreenSimplificationMetric,
  SimplificationMetrics,
  TruncatedScreenMetric,
  ValidatedDesignIR,
  IRValidationError,
  IRValidationResult,
  ValidationFailure,
  VariantElementState,
  VariantMappingIR,
  VariantMuiProps,
  VariantStateSnapshot,
  VariantStateStyle
} from "./types-ir.js";

export type {
  EditSessionEvent,
  EditSessionGitStatus,
  EditSessionRecord,
  EditSessionSyncState,
  EditSessionTypecheckDiagnostic,
  EditSessionTypecheckResult,
  EditableFileNode,
  FileContentRecord,
  SaveOperationCommit,
  SaveOperationResult
} from "./types-edit-session.js";

export type {
  KpiAlert,
  KpiAlertCode,
  KpiBaselineComparison,
  KpiBucket,
  KpiDurationStats,
  KpiRateStats,
  KpiTrendBucket,
  PortfolioKpiResponse,
  PortfolioKpiSnapshot,
  ProjectKpiResponse,
  ProjectKpiSnapshot
} from "./types-kpi.js";

export type {
  FigmaMcpEnrichment,
  FigmaMcpNodeHint,
  JobDeltaSummary,
  JobDiffPreview,
  JobEvent,
  JobInput,
  JobLlmMetrics,
  JobMetrics,
  JobPreview,
  JobQueueState,
  JobRecord,
  JobResult,
  JobSourceMeta,
  JobStage,
  JobWarning,
  LatestSuccessJobResponse,
  LatestSuccessPreview,
  ProjectActivity,
  ProjectDeleteResponse,
  ProjectSummary,
  RepoConfig,
  ReviewEvidenceRecord,
  ReviewEvidenceSummary,
  UiGateResult
} from "./types-job.js";
