/**
 * Wave 1 POC fixture loader (Issue #1366).
 *
 * The Wave 1 end-to-end POC is gated by two public, fully synthetic Figma
 * fixtures plus their visual sidecar companions. This module is the
 * single source of truth for resolving a fixture id into the on-disk
 * inputs the harness consumes:
 *
 *   - `<fixtureId>.figma.json`   — normalised Figma input.
 *   - `<fixtureId>.visual.json`  — multimodal visual sidecar batch.
 *
 * Both files live under `src/test-intelligence/fixtures/` and are
 * intentionally checked-in plain JSON so they can be diffed in PRs and
 * regenerated by hand when the Figma source moves.
 */

import { readFile } from "node:fs/promises";
import { join } from "node:path";

import {
  WAVE1_POC_FIXTURE_IDS,
  type Wave1PocFixtureId,
  type VisualScreenDescription,
} from "../contracts/index.js";
import type { IntentDerivationFigmaInput } from "./intent-derivation.js";

const FIXTURES_DIR = join(new URL(".", import.meta.url).pathname, "fixtures");

/** Re-export for convenience so callers do not have to reach into `contracts`. */
export { WAVE1_POC_FIXTURE_IDS, type Wave1PocFixtureId };

export interface LoadedWave1PocFixture {
  fixtureId: Wave1PocFixtureId;
  /** Normalised Figma input ready for `deriveBusinessTestIntentIr`. */
  figma: IntentDerivationFigmaInput;
  /** Visual sidecar batch covering the same screens as `figma`. */
  visual: VisualScreenDescription[];
  /** Absolute on-disk path of the loaded Figma fixture. */
  figmaPath: string;
  /** Absolute on-disk path of the loaded visual sidecar fixture. */
  visualPath: string;
}

/**
 * Whether `value` matches one of the registered Wave 1 POC fixture ids.
 * Useful at API boundaries that accept user-provided strings.
 */
export const isWave1PocFixtureId = (
  value: unknown,
): value is Wave1PocFixtureId => {
  return (
    typeof value === "string" &&
    (WAVE1_POC_FIXTURE_IDS as readonly string[]).includes(value)
  );
};

/**
 * Load a Wave 1 POC fixture into the shapes the harness consumes. Reads
 * the JSON files lazily and returns plain in-memory objects; both files
 * are required and `fixtureId` MUST belong to `WAVE1_POC_FIXTURE_IDS`.
 *
 * `loadWave1PocFixture` does NOT validate the visual sidecar against the
 * sidecar gate — that is the harness's job, since validation is one of
 * the steps the POC exercises.
 */
export const loadWave1PocFixture = async (
  fixtureId: Wave1PocFixtureId,
): Promise<LoadedWave1PocFixture> => {
  if (!isWave1PocFixtureId(fixtureId)) {
    throw new RangeError(
      `loadWave1PocFixture: unknown fixtureId "${String(fixtureId)}". ` +
        `Allowed: ${WAVE1_POC_FIXTURE_IDS.join(", ")}.`,
    );
  }
  const figmaPath = join(FIXTURES_DIR, `${fixtureId}.figma.json`);
  const visualPath = join(FIXTURES_DIR, `${fixtureId}.visual.json`);
  const [figmaRaw, visualRaw] = await Promise.all([
    readFile(figmaPath, "utf8"),
    readFile(visualPath, "utf8"),
  ]);
  const figma = JSON.parse(figmaRaw) as IntentDerivationFigmaInput;
  const visual = JSON.parse(visualRaw) as VisualScreenDescription[];
  return { fixtureId, figma, visual, figmaPath, visualPath };
};
