/**
 * Wave 1 Validation fixture loader (Issue #1366).
 *
 * The Wave 1 validation harness is gated by two public, fully synthetic Figma
 * fixtures plus their visual sidecar companions. This module is the
 * single source of truth for resolving a fixture id into the on-disk
 * inputs the harness consumes:
 *
 *   - `<fixtureId>.figma.json`   — normalised Figma input.
 *   - `<fixtureId>.visual.json`  — multimodal visual sidecar batch.
 *
 * Both files live under `src/test-intelligence/fixtures/` and are
 * intentionally checked-in plain JSON so they can be diffed in PRs and
 * regenerated by hand when the Figma source moves.
 */

import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

import {
  ALLOWED_VISUAL_SIDECAR_INPUT_MIME_TYPES,
  WAVE1_VALIDATION_FIXTURE_IDS,
  type VisualScreenDescription,
  type VisualSidecarCaptureInput,
  type VisualSidecarInputMimeType,
  type Wave1ValidationFixtureId,
} from "../contracts/index.js";
import type { IntentDerivationFigmaInput } from "./intent-derivation.js";

const FIXTURES_DIR = join(new URL(".", import.meta.url).pathname, "fixtures");

/** Re-export for convenience so callers do not have to reach into `contracts`. */
export { WAVE1_VALIDATION_FIXTURE_IDS, type Wave1ValidationFixtureId };

export interface LoadedWave1ValidationFixture {
  fixtureId: Wave1ValidationFixtureId;
  /** Normalised Figma input ready for `deriveBusinessTestIntentIr`. */
  figma: IntentDerivationFigmaInput;
  /** Visual sidecar batch covering the same screens as `figma`. */
  visual: VisualScreenDescription[];
  /** Absolute on-disk path of the loaded Figma fixture. */
  figmaPath: string;
  /** Absolute on-disk path of the loaded visual sidecar fixture. */
  visualPath: string;
  /** Optional colocated synthetic image/mask fixture for visual-sidecar provenance. */
  visualImagePath?: string;
  /** SHA-256 hex of the optional visual image/mask fixture bytes. */
  visualImageSha256?: string;
}

/**
 * Whether `value` matches one of the registered Wave 1 Validation fixture ids.
 * Useful at API boundaries that accept user-provided strings.
 */
export const isWave1ValidationFixtureId = (
  value: unknown,
): value is Wave1ValidationFixtureId => {
  return (
    typeof value === "string" &&
    (WAVE1_VALIDATION_FIXTURE_IDS as readonly string[]).includes(value)
  );
};

/**
 * Load a Wave 1 Validation fixture into the shapes the harness consumes. Reads
 * the JSON files lazily and returns plain in-memory objects; both files
 * are required and `fixtureId` MUST belong to `WAVE1_VALIDATION_FIXTURE_IDS`.
 *
 * `loadWave1ValidationFixture` does NOT validate the visual sidecar against the
 * sidecar gate — that is the harness's job, since validation is one of
 * the steps the production validation flow exercises.
 */
export const loadWave1ValidationFixture = async (
  fixtureId: Wave1ValidationFixtureId,
): Promise<LoadedWave1ValidationFixture> => {
  if (!isWave1ValidationFixtureId(fixtureId)) {
    throw new RangeError(
      `loadWave1ValidationFixture: unknown fixtureId "${String(fixtureId)}". ` +
        `Allowed: ${WAVE1_VALIDATION_FIXTURE_IDS.join(", ")}.`,
    );
  }
  const figmaPath = join(FIXTURES_DIR, `${fixtureId}.figma.json`);
  const visualPath = join(FIXTURES_DIR, `${fixtureId}.visual.json`);
  const visualImagePath = join(FIXTURES_DIR, `${fixtureId}.mask.svg`);
  const [figmaRaw, visualRaw] = await Promise.all([
    readFile(figmaPath, "utf8"),
    readFile(visualPath, "utf8"),
  ]);
  const figma = JSON.parse(figmaRaw) as IntentDerivationFigmaInput;
  const visual = JSON.parse(visualRaw) as VisualScreenDescription[];
  let visualImageSha256: string | undefined;
  try {
    const visualImage = await readFile(visualImagePath);
    visualImageSha256 = createHash("sha256").update(visualImage).digest("hex");
  } catch (err) {
    if (
      typeof err !== "object" ||
      err === null ||
      (err as { code?: string }).code !== "ENOENT"
    ) {
      throw err;
    }
  }
  return {
    fixtureId,
    figma,
    visual,
    figmaPath,
    visualPath,
    ...(visualImageSha256 !== undefined
      ? { visualImagePath, visualImageSha256 }
      : {}),
  };
};

/**
 * Mapping from a fixture id to the colocated capture image filename and
 * MIME type. The capture is intentionally tiny (a deterministic 4×4
 * PNG) so it can be checked in to the repo without inflating the
 * fixtures directory.
 */
const CAPTURE_FIXTURE_MIME: Record<
  Wave1ValidationFixtureId,
  VisualSidecarInputMimeType
> = {
  "validation-onboarding": "image/png",
  "validation-payment-auth": "image/png",
};

/**
 * Result of loading the capture-side fixture for a Wave 1 Validation fixture.
 * The captures cover every screen in the companion `*.visual.json`
 * fixture so the harness's visual-sidecar pipeline can exercise the
 * same screens the deterministic mock-only path emits.
 */
export interface LoadedWave1ValidationCaptureFixture {
  fixtureId: Wave1ValidationFixtureId;
  captures: VisualSidecarCaptureInput[];
  /** SHA-256 hex of the original PNG bytes that backs every capture. */
  imageSha256: string;
  /** Absolute on-disk path of the capture PNG. */
  imagePath: string;
}

/**
 * Load the deterministic capture fixture for a Wave 1 Validation fixture. Each
 * capture reuses the same single PNG so the test surface is small and
 * the byte stream is byte-stable across runs. The screen ids match
 * the companion `*.visual.json` fixture verbatim, which is what lets
 * the visual-sidecar gate compare sidecar output against the Figma IR.
 *
 * Throws if the capture image is missing — callers should fail loudly
 * rather than silently fall back to the fixture-only path.
 */
export const loadWave1ValidationCaptureFixture = async (
  fixtureId: Wave1ValidationFixtureId,
): Promise<LoadedWave1ValidationCaptureFixture> => {
  if (!isWave1ValidationFixtureId(fixtureId)) {
    throw new RangeError(
      `loadWave1ValidationCaptureFixture: unknown fixtureId "${String(fixtureId)}"`,
    );
  }
  const mimeType = CAPTURE_FIXTURE_MIME[fixtureId];
  if (
    !(ALLOWED_VISUAL_SIDECAR_INPUT_MIME_TYPES as readonly string[]).includes(
      mimeType,
    )
  ) {
    throw new RangeError(
      `loadWave1ValidationCaptureFixture: unsupported mime type for ${fixtureId}`,
    );
  }
  const imagePath = join(FIXTURES_DIR, `${fixtureId}.capture.png`);
  const bytes = await readFile(imagePath);
  const base64Data = Buffer.from(bytes).toString("base64");
  const imageSha256 = createHash("sha256").update(bytes).digest("hex");

  // Reuse the screens declared by the visual fixture so the pipeline
  // covers the same set the deterministic path covers. We only need
  // screen ids + names to drive the captures.
  const visualPath = join(FIXTURES_DIR, `${fixtureId}.visual.json`);
  const visualRaw = await readFile(visualPath, "utf8");
  const visual = JSON.parse(visualRaw) as VisualScreenDescription[];

  const captures: VisualSidecarCaptureInput[] = visual.map((screen) => {
    const capture: VisualSidecarCaptureInput = {
      screenId: screen.screenId,
      mimeType,
      base64Data,
    };
    if (screen.screenName !== undefined) {
      capture.screenName = screen.screenName;
    }
    if (screen.capturedAt !== undefined) {
      capture.capturedAt = screen.capturedAt;
    }
    return capture;
  });
  return { fixtureId, captures, imageSha256, imagePath };
};
